<?php

namespace Lewik\BoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LotRepository extends EntityRepository
{
}
