<?php

namespace Lewik\BoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Test1419184895Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Test1419184895Repository extends EntityRepository
{
}
