<?php

namespace Lewik\BoManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BoConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoConfigurationRepository extends EntityRepository
{
}
